/*
1. Sales KPIs
*/

SELECT SUM(Sales) AS TotalSales FROM Superstore; --Total Sales


SELECT Category, SUM(Sales) AS TotalSales --Total Sales by Category
FROM Superstore
GROUP BY Category
ORDER BY TotalSales DESC;

SELECT Region, SUM(Sales) AS TotalSales --Total Sales by Region
FROM Superstore
GROUP BY Region
ORDER BY TotalSales DESC;

/*
2. Customer Insights
*/

SELECT TOP 10 [Customer ID], [Customer Name], SUM(Sales) AS TotalSales --Top 10 Customers
FROM Superstore
GROUP BY [Customer ID], [Customer Name]
ORDER BY TotalSales DESC;

SELECT AVG(CustomerSales) AS AvgSalesPerCustomer --Average revenue generated by each customer
FROM (
  SELECT [Customer ID], SUM(Sales) AS CustomerSales
  FROM Superstore
  GROUP BY [Customer ID]
) AS CustomerSalesData;

/*
3. Product-Level KPIs
*/

SELECT TOP 10 [Product ID], [Product Name], SUM(Sales) AS TotalSales --Top 10 Products
FROM Superstore
GROUP BY [Product ID], [Product Name]
ORDER BY TotalSales DESC

SELECT [Category], [Sub-Category], SUM(Sales) AS TotalSales --sub-category performance within categories
FROM Superstore
GROUP BY [Category], [Sub-Category]
ORDER BY TotalSales DESC;

/*
4. Operational KPIs
*/

SELECT AVG(DATEDIFF(DAY, [Order Date], [Ship Date])) AS AvgFulfillmentTime --Order Fulfillment Time
FROM Superstore;


SELECT COUNT(*) AS LateOrders --Late Shipments
FROM Superstore
WHERE DATEDIFF(DAY, [Order Date], [Ship Date]) > 5;

/*
5. Regional Insights
*/

SELECT Region, SUM(Sales) AS TotalSales,	--Sales Contribution by Region
       (SUM(Sales) * 100.0 / (SELECT SUM(Sales) FROM Superstore)) AS SalesPercentage
FROM Superstore
GROUP BY Region
ORDER BY TotalSales DESC;


SELECT Region, Category, SUM(Sales) AS TotalSales --Best-Selling Categories by Region
FROM Superstore
GROUP BY Region, Category
ORDER BY Region, TotalSales DESC;


/*
6. Time-Based Trends
*/

SELECT YEAR([Order Date]) AS Year, MONTH([Order Date]) AS Month, SUM(Sales) AS TotalSales --Monthly Sales Trend
FROM Superstore
GROUP BY YEAR([Order Date]), MONTH([Order Date])
ORDER BY Year, Month;


SELECT Top 10 [Order Date], SUM(Sales) AS TotalSales --Peak Sales Periods
FROM Superstore
GROUP BY [Order Date]
ORDER BY TotalSales DESC

